# Dockerfile.dev
FROM node:22.17-alpine AS dev
RUN apk add --no-cache python3 make g++
WORKDIR /usr/src/app
COPY ./package.json ./pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install
COPY . .
EXPOSE 3000
CMD ["pnpm", "dev"]
