services:
  frontend:
    container_name: v2-frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    ports:
      - "3001:3000"
    networks:
      - app
    depends_on:
      - postgres

  postgres:
    container_name: v2-postgres
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: app-admin
      POSTGRES_PASSWORD: app-admin-pass
      POSTGRES_DB: app-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
    name: app
    driver: bridge
